trigger:
  branches:
    include:
    - master
  paths:
    include:
    - TheGuild-Angular

pool:
  name: Default

variables:
  appDir: TheGuild-Angular

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '>=10'
    checkLatest: true
  displayName: Install Node.js

- script: npm ci
  workingDirectory: $(appDir)
  displayName: npm ci

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  inputs:
    SonarCloud: 1902-feb18-net_The_Guild_Angle
    organization: 1902-feb18-net
    projectKey: 1902-feb18-net_The_Guild_Angle
    projectName: The_Guild_Angular
    scannerMode: CLI
  displayName: Prepare analysis on SonarCloud

- script: npm run build
  workingDirectory: $(appDir)
  displayName: npm run build

- script: npm run lint
  workingDirectory: $(appDir)
  displayName: npm run lint

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: Run code analysis

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: Publish quality gate result

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service deploy: project2theGuildAngular'
  inputs:
    azureSubscription: 'Free Trial (35bc8ed2-6317-49d4-9955-4f96d2723eb3)'
    WebAppName: project2theGuildAngular
    packageForLinux: $(appDir)/dist/TheGuild-Angular
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(appDir)/dist/TheGuild-Angular
    artifactName: app
  displayName: Publish app artifact
